name: Freifunk Bremen
markdown: redcarpet
pygments: true

timezone: Europe/Berlin
encoding: UTF-8

future: true
permalink: /blog/:year/:month/:day/:title.html

paginate: 5
paginate_path: blog/page/:num
